name: Test Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script JS
        run: |
          echo "Hello depuis GitHub Actions 🚀"
          node -v